export const myProjects = [
  {
    projectTitle: "E-Commerce Platform (Real Business Project)",
    category: ["react", "html", "css"],
    imgPath: "../../../images/BookStoreApp.png",
    gitPath: "https://github.com/HannaFarha/Book-Store-app.git",
    web: "https://7lwlak.netlify.app/",
    description: "Built an e-commerce website for a real business project in Syria, designed to sell imported products online. The project combines a fast, user-friendly web experience with planned Instagram marketing campaigns to attract and convert customers. Focused on performance, UX, and conversion-ready structure.",
  },
  {
    projectTitle: "Full-Stack Media Platform",
    category: ["node", "express"],
    imgPath: "../../../images/VinylePage.PNG",
    gitPath: "https://github.com/HannaFarha/M3-Project-Frontend.git",
    web: "https://vinyl-groove-app.netlify.app/",
    description: "Built a full-stack application using React, Express, and MongoDB with secure authentication. Focused on performance, clean structure, and intuitive user experience to support engagement and usability. Demonstrates my ability to develop scalable and user-focused systems.",
  },
  {
    projectTitle: "Interactive Food Game (User Engagement Project)",
    category: ["js", "html", "css"],
    imgPath: "../../../images/HealtyFoodGame.png",
    gitPath: "https://github.com/HannaFarha/my-project.git",
    web: "https://hannafarha.github.io/my-project/",
    description: "Developed an interactive browser-based game using JavaScript, focused on user interaction and real-time responsiveness.Designed to create an engaging and playful experience that keeps users active and increases time spent on the application.This project demonstrates my understanding of user engagement, interaction design, and how gamification can enhance user retention..",
  },
  {
    projectTitle: "Next.JS",
    category: ["Next.JS", "React"],
    imgPath: "../../../images/Next.JS.png",
    gitPath: "https://github.com/HannaFarha/Next.js.git",
    web: "https://next-js-rouge-seven.vercel.app/",
    description: "Explored Next.js and server-side rendering to improve performance and SEO. Focused on faster loading and better indexing to enhance visibility in search engines.",
  },
  {
    projectTitle: "Recipe Platform (UX-Focused Application)",
    category: ["react", "node", "css", "html"],
    imgPath: ".../../../images/Recipe.png",
    gitPath: "https://github.com/HannaFarha/RecipeBook.git",
    description: "Built a simple and intuitive recipe management application using React.Focused on usability, fast interaction, and clean UI to improve user experience and engagement.Demonstrates my approach to building user-centered applications..",
  },
  {
    projectTitle: "Workforce Tracking System (Flink Operations)",
    category: ["php", "html", "css"],
    imgPath: "../../../images/Flink.PNG",
    gitPath: "https://github.com/HannaFarha/FlinkProjekt.git",
    description: "Built a workforce tracking system to manage bike usage and reporting at Flink.Improved accountability and workflow efficiency by enabling structured data entry and automated reporting to management.Demonstrates problem-solving and real-world system design",
  },
  {
    projectTitle: "Task & Communication System (Restaurant Workflow)",
    category: ["react", "jsx", "css", "express", "Database"],
    imgPath: "../../../images/to-do-liste-fehler.jpg",
    web: "https://wrap4friends-hanna-farha.netlify.app",
    gitPath: "https://github.com/HannaFarha/ToDoList",
    description: "Built a task management system to improve communication and workflow between staff and kitchen operations.Enabled clear task tracking and real-time updates to reduce errors and improve efficiency.Demonstrates problem-solving and practical system design.."
  },
];